### ISSUE TITLE
How to install Admin Docs?

### ISSUE THREAD

**Issue by cesardft** [farridav/django-jazzmin#127]
Hi, guys!

Congratulations for the project!

I have one question: how do i install the Admin Docs?

**Comment by farridav** [comment]
The admin docs is a contrib app built and maintained my Django, all we did was add a little bit of jazz to it :)

Heres a link the the django docs explaining how it works and how to enable it

https://docs.djangoproject.com/en/3.1/ref/contrib/admin/admindocs/#overview

Please re-open the issue if you find any problems caused by jazzmin ..

**Comment by PrynsTag** [comment]
I am using Django 4.0.2 and installing the [Admin Docs](https://docs.djangoproject.com/en/4.0/ref/contrib/admin/admindocs/) currently has a breaking UI. 

See image bellow:

![image](https://user-images.githubusercontent.com/56314705/161347643-8c526d53-03dc-4b77-8c55-f3f23153faca.png) 

There is an github issue #44 which suggests that is not the desired outcome and also Django 4.0 is supported #366 under this issue.
