### ISSUE TITLE
NoReverseMatch when trying to create new objects

### ISSUE THREAD

**Issue by yovelcohen** [farridav/django-jazzmin#190]
Hi, trying to create new objects in one of my models but getting this error:

```
NoReverseMatch at /admin/consumer_api/site/add/
Reverse for 'consumer_api_site_change' with arguments '('',)' not found. 1 pattern(s) tried: ['admin/consumer_api/site/(?P<object_id>.+)/change/$']
```

this model has a M2M relationship if that's usefull, it seems like an error in the template, but I don't Django templates so much,
so I'm not sure what's up here

**Comment by TysonRV** [comment]
@yovelcohen It looks like you probably don't have `add` permissions for that model and somewhere on the templates is missing to check that before displaying the reverse that leads to it. 

Could you do a couple of things?
- Comment out `jazzmin` app from the `INSTALLED_APPS` on the settings and reload, just to make sure the problem is in jazzmin.
- If it doesn't happen anymore, please share with us the `AdminModel` and the `Model` classes that you are using for both models: the model that's failing and its m2m relationship. This will help us reproduce the error. 

If the problem is not in jazzmin, that means you might have some custom templates that need fixing.
Thanks for submitting the issue, looking forward to seeing those models!

**Comment by yovelcohen** [comment]
@TysonRV it seems that it happens without jazzmin as well, so it must be something I changed in the ModelAdmin it self, thanks a lot for the help even so.

**Comment by TysonRV** [comment]
@yovelcohen anytime! Thanks for the update 😄
