### ISSUE TITLE
'import_export_tags' is not a registered tag library. Must be one of:

### ISSUE THREAD

**Issue by HT-Moh** [farridav/django-jazzmin#309]
Hi 

running the command `python manage compilescss`   give the following error: 

```
Invalid template /usr/local/lib/python3.8/site-packages/jazzmin/templates/admin/import_export/export.html: 'import_export_tags' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_tree_list_tags
admin_urls
bower
cache
category_tags
countries
crispy_forms_field
crispy_forms_filters
crispy_forms_tags
crispy_forms_utils
cropping
djmoney
easy_thumbnails_tags
embed_video_tags
i18n
jazzmin
l10n
log
notifications_tags
order_tags
post_office
sass_tags
sekizai_tags
static
thumbnail
tp_product_utils
tp_utils
tz
```

Note:
The command from sass compiler [django-sass-processor](https://github.com/jrief/django-sass-processor)

**Comment by farridav** [comment]
Do you have import_export in your project ?

**Comment by farridav** [comment]
Nope definitely not, it's a package we provide 3rd party support for, but I hadn't realised that template preprocessors would pull those templates in... 

U may need to rethink our 3rd party support for packages that require their own template tags

**Comment by HT-Moh** [comment]
So what do you suggest to not use django-jazzmin?

**Comment by farridav** [comment]
These errors do not appear to stop django-sass-processor from collecting and processing css files (I have just tried this myself)

Though i acknowledge it is a bit annoying seeing it there in red .. Its because `django-sass-processor` is collecting and parsing all of the templates in all apps, including optional templates we have included for third party support, which contain template tags that will only be available if you have the respective app installed, and in your `INSTALLED_APPS` list.

Short term, this shouldn't stop you using jazzmin, but longer term, I think we need to re-think the way we provide 3rd party support, as theres a long list of requests for support because our templates deviate significantly from standard django admin (which is largely the reason people want to use jazzmin in the first place)
