### ISSUE TITLE
I have to ask. Is Jazzmin unmaintained?

### ISSUE THREAD

**Issue by Pijuli** [farridav/django-jazzmin#363]
There has been many issues without answer.
There are 13 PRs open wishing to fix things.
No updates since september.

**Just to be clear, not demanding anything, just asking.**

cc/ @farridav

**Comment by farridav** [comment]
I have been outbid the loop for a little while due to other commitments, though I can see there is alot of contributions coming in, and am going to carve out some some time every week to get these PRs reviewed and merged.

I'll start looking into these on Monday, apologies for being absent, and thankyou for your continued interest in the project.

**Comment by farridav** [comment]
Closing issue, as im able to allocate some time to this now, and have made a start on the backlog

**Comment by Pijuli** [comment]
Good to hear!
I'll keep doing as much PRs as I know ;)
