### ISSUE TITLE
Attempted access to '/static/images/XXX.png' denied for Amazon S3

### ISSUE THREAD

**Issue by rene-schwabe** [farridav/django-jazzmin#520]
We use Amazon S3 as a CDN for our images. We have added a "site_logo" via Settings.py:
"site_logo": "/static/images/XXX.png",

I can see the image in the S3 bucket and it is publicly accessible.

However, we cannot call the Django admin because we get the message "Bad Request (400)" - Attempted access to '/static/images/XXX.png' denied.

Is it possible to use jazzmin logo for admin with Amazon S3?

**Comment by thencke** [comment]
I have a similar issue with font-awesome icons in sidebar/buttons, it is not applying the aws signature in the get request.

Did you fin any solution @rene-schwabe ?

**Comment by enoquesantos** [comment]
I solve this adding only the image path, don't add `/static/` because jazzmin [will concat](https://github.com/farridav/django-jazzmin/blob/c408e996e1c716d65f9ef199a630f88131380547/jazzmin/templates/admin/base.html#L68) with `STATIC_URL`.

I'm using DigitalOcean Spaces with Django and image appears normally after collectstatic.

Instead of
```
/static/images/XXX.png
```

Use this:
```
images/XXX.png
```

I hope this helps

**Comment by rene-schwabe** [comment]
> I solve this adding only the image path, don't add `/static/` because jazzmin [will concat](https://github.com/farridav/django-jazzmin/blob/c408e996e1c716d65f9ef199a630f88131380547/jazzmin/templates/admin/base.html#L68) with `STATIC_URL`.
> 
> I'm using DigitalOcean Spaces with Django and image appears normally after collectstatic.
> 
> Instead of
> 
> ```
> /static/images/XXX.png
> ```
> 
> Use this:
> 
> ```
> images/XXX.png
> ```
> 
> I hope this helps

Thanks, that's the solution
